### ISSUE TITLE
Document that non-UNIX environments are not supported

### ISSUE THREAD

**Issue by lpil** [Olian04/gleam_stdin#1]
Hello!

The description of this package claims that only the browser is not supported, but it also does not work on Windows or any other environment without stdin being fd 0. It would be fab to document this.

Thank you,
Louis

**Comment by Olian04** [comment]
@lpil I just tried it on my Win 10 machine and it works just fine. Both targeting Erlang and targeting JavaScript. What OS did you run it on when you encountered these issues?

**Comment by Olian04** [comment]
~~I did find out that it doesn't support Deno yet though. So I will see if I can fix that #2.~~
This is now fixed.
